# Site settings
title: "Refugee Tech"
email: "info@refugeetech.com"
description: "Combining creative minds and technology, innovating together."
baseurl: ""
url: "http://refugeetech.com"
twitter_username: "refugeetech"
facebook_username: "refugeetech"

# Build settings
markdown: kramdown
sass:
  style: compressed
